### ISSUE TITLE
PyCS Tutorial

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#1]
@milanwilliams  We have a skeleton class that we can use to call PyCS from, but it doesn't yet call PyCS. What we need is to figure out how PyCS works by running the PyCS demo1 routine in a notebook, and then editing the SLTimer code so that it can do the same things. The PyCS demo1 is explained in the [online tutorial](http://pycs.readthedocs.io/en/latest/tutorial/demo1.html), so that's the place to start; you can [read the PyCS code online](https://github.com/COSMOGRAIL/PyCS/tree/master/demo/demo1) as well. What we are after is the _simplest possible light curve analysis_ :-)
- [x] Plot the trial data in the notebook using a PyCS plotting routine #8
- [x] Check notebook runs in Binder #11 
- [x] Implement the time delay estimation in the notebook #7 
- [x] Re-order and streamline #14

**Comment by drphilmarshall** [comment]
Hi @TomGlanzman - I just got `PyCS` working, and updated the README and the setup files to explain how I did it. I'm now setting up travis CI as well to make sure. I'll add a starter notebook for Milan to work on this week. Watch this space! :-)

**Comment by drphilmarshall** [comment]
Tutorial is now finished, modulo a couple of PyCS bugs.
