### ISSUE TITLE
Test the TDC2 Gateway Data

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#40]
Over in the SLTimeDelayChallenge, @liaokai181 is making 10 example "gateway" datasets to give to the TDC1 Good Teams so that they can prepare for TDC2. We need to run `SLTimer` on them, to see if we can infer the time delays accurately. We'll do the code development here, including keeping the example notebook up to date, but do the testing in the Evil (private) [SLTimeDelayChallenge repo](https://github.com/DarkEnergyScienceCollaboration/SLTimeDelayChallenge).
- [x] Get 10 multi-filter light curve datasets from Kai https://github.com/DarkEnergyScienceCollaboration/SLTimeDelayChallenge/issues/164
- [x] Send `PyCS` stdout to a logfile #20 
- [x] Start "TDC2 Gateway Test" notebook, and read in and make spline models for each dataset
- [x] Compare inferred time delays with true values and discuss
- [x] Check initialization at the truth, comparing final best fit `runresults.q2` misfit statistics #41
- [ ] Investigate auto-initialization following advice from Malte and Vivian #42 
- [ ] Generate approximate posterior samples as well, and write out to file #33
- [x] Upgrade whitening #39

**Comment by drphilmarshall** [comment]
I updated the [TDC2 example notebook](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/SLTimer_TDC2_Example.ipynb) to use one of Kai's new (first 10) datasets - it's a double, so I needed to fix a couple of hard-coded things but I can now get `pycs` time delay estimates, of around +9 days. Problem is, the true delay is 55 days. I think we are stuck at a local likelihood maximum, so now need to experiment with varying the starting position (or something). Strategy suggestions most welcome, @mtewes ! :-)

**Comment by mtewes** [comment]
Hi @drphilmarshall! While preparing for the TDC1 last year, this was the point at which we (with @vbonvin) took the weird decision to just eyeball all those curve pairs :-)

Indeed the main `pycs` methods `spl` and `regdiff` are not well suited to select among local likelihood maxima. One could try to hack something together building upon parts of those methods, but we haven't gone very far in this direction. We (especially @vbonvin) did play with a spline-based automatic procedure, summarized in Appendix A of Bonvin et al. 2016 (http://dx.doi.org/10.1051/0004-6361/201526704). If interested, we could try to put together a "Stage 1" black-box function running this. Might be a solution.

It became clear that coming anywhere close to our D3CS-results with a simple global approach is challenging. To identify good candidate delays automatically (and without switching to a full-bayesian physical-model approach) my feeling is that some simple methods, _without_ iterative optimizations of intrinsic and extrinsic curves might be best suited. Say a multiscale wavelet decomposition of the individual curves to split up the signals into different time scales, and then finding good peaks in 2D-correlations (delay versus scale) of these decompositions. Followed maybe by supervised machine learning to judge these candidates. Such technical recipes would be interesting for a "Stage 1" challenge (e.g. identifying approximate delays securely and without outliers, without any prior idea of what the delay could be). But in real life and for TDC2 one could use the lens model information and a prior H0 to get a prior on the time delay. And of course eyeball the curves anyway :)

Note that technically, all the notebook has to do for `spl` to run fine, is to set time shifts of the `pycs.gen.lc.lightcurve` objects so that the time delay is approximatively correct, before starting the  method.

I'm happy to go deeper into this, let me know what you think!

**Comment by drphilmarshall** [comment]
Thanks Malte, some good thoughs here :-) I think I'll try drawing initial
delays from the H0-determined prior. It looks to me as though the local
likelihood maximum really is lower than the global one - the fit does not
look that good. What's the easiest way to get `pycs` to return the log
likelihood of the best fit parameters?

**Comment by mtewes** [comment]
> It looks to me as though the local likelihood maximum really is lower than the global one - the fit does not look that good.

Yes, for easy cases this is mostly true. A problem is that for more difficult cases there will always be one or several apparent "likelihood" maxima (and often apparently absolute), which have nothing to do with the true delay. For instance, shifting the curves by almost one season length (i.e., small overlap) might lead to small fit residuals even if the microlensing model has relatively few parameters.

> What's the easiest way to get `pycs` to return the log likelihood of the best fit parameters?

The `SLTimer` method `optimize_spline_model()` returns a `spline`, and this spline has an attribute `spline.lastr2nostab`, which is a sum of squared weighted residuals (defined here: https://github.com/COSMOGRAIL/PyCS/blob/master/pycs/gen/spl.py#L887)
When using `multirun` (resulting in a pickled `runresults` object), those values should be in `runresults.q2` in the same way as `runresults.tsarray` contains the estimated delays.

**Comment by vbonvin** [comment]
> > It looks to me as though the local likelihood maximum really is lower than the global one - the fit does not look that good.
> > Yes, for easy cases this is mostly true. A problem is that for more difficult cases there will always be one or several apparent "likelihood" maxima (and often apparently absolute), which have nothing to do with the true delay. For instance, shifting the curves by almost one season length (i.e., small overlap) might lead to small fit residuals even if the microlensing model has relatively few parameters.

Hi folks,

As @mtewes mentioned, we played a bit with an automatic time-delay finder in the Appendix of Bonvin2016. The idea was not to find precisely the delay but to help discover plausible solution(s) faster than simply eyeball the curves. We had the same problem about local minimas if starting from a "wrong" initial guess (see Fig. A.1 of Bonvin2016). To overpass this, we started using both the depth of the minimas and the amplitude of the microlensing variability explained in Sec. A.2 of Bonvin2016. As far as I recall, I obtained a quite good quality (i.e. a correct guess on more than 90% of the estimates) on the curves we labeled "secure" and "plausible" in the TDC1 (~60% of the total sample)

**Comment by drphilmarshall** [comment]
Thanks @vbonvin @mtewes, these suggestions are most helpful! 

Chun-Hao To ( @chto ) is a Stanford grad student working with Steve Kahn ( @stevkahn ) and me - he is going to investigate simple semi-automatic initialization, and also sample generation (#33), to help get ready for TDC2. Chun-Hao, please read through the comments above as you get started with the notebooks. I'll issue the initialization task so we can focus on it in a separate thread.

We can use the [TDC2 Example notebook](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/issue/40/tdc2gatewaytest/notebooks/SLTimer_TDC2_Example.ipynb) as our workplace - let's try and upgrade it so that the time delay is _just found_. Note that the development branch for this work is `issue/40/tdc2gatewaytest` - that's the one to submit pull requests to.

**Comment by mtewes** [comment]
Hi @chto, feel free to ask us for help if you run into problems!

**Comment by drphilmarshall** [comment]
Hi @mtewes , hi @vbonvin 

@chto and I have a notebook to show you, [here](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/SLTimer_TDC2_Analysis.ipynb). In it we analyze just the first TDC2 gateway dataset, and look at how the best fit chi-squared at fixed time delay varies as we scan through the time delay (it's a double, so there's only one time delay). We're not getting good fits, and we see a lot of wild variation in chi-squared. We've laid out our conclusions for you, and would love to get your feedback! Thanks :-)

**Comment by vbonvin** [comment]
Hi all,

Browsing through your notebook, I saw this:

> The chi-squared minimum at -55 days seeems persistent, betweem whitened data and single-filter data. We need to check with Kai what the definition of the time delay is (B-A or A-B).

And if I understand correctly, you are playing with [this light curves](http://www.slac.stanford.edu/~pjm/LSST/DESC/SLTimeDelayChallenge/release/tdc2/gateway/tdc2-gateway-1.txt), whose true delay is 55.37 days

The definition of the time delay was reversed between PyCS and the TDC1 data, so it might be that your estimation is good enough. In PyCS, if you measure a negative delay between A and B (say -55 days), it means that the variations in B are observed 55 days later than in A. In your plots, you seems to shift B by + 55 days and the fit the splines. Try to start by shifting it in the other direction, i.e. -55 days. Even if you run opt_rough before doing the spline fit, it's more than likely it won't find a good initial guess, especially on noisy / poorly sampled data.

FYI, I ran my Automated Stage-1 procedure from Appendix A of [Bonvin2016](https://arxiv.org/pdf/1506.07524v2.pdf) on the whole data, and then and u and i band and I also get a best guess around -55 days.

**Comment by chto** [comment]
Hi @vbonvin , 
Thanks for the reply. 
We have confirmed with Kai Liao that it is T_B- T_A =55.  
The way I make my plots shift light curve B and fit spline function with parameter "shifttime=False". I then calculate chisquare and set TAB=B.shifttime. (A.shiftime=0) I think this is the reason why there is a flip sign. 

But given this, the chisquare value for t=-55 is still very large. Could you let me know the chisquare you got when you ran Automated Stage-1 procedure? Thanks.

**Comment by vbonvin** [comment]
> We have confirmed with Kai Liao that it is T_B- T_A =55.

Which means that variations seen in the image B are late by 55 days with respect to the variations in image A, right ?

> But given this, the chisquare value for t=-55 is still very large. Could you let me know the chisquare you got when you ran Automated Stage-1 procedure? Thanks.

Although we use spline fits in the automated procedure, we don't directly use the chi-square from the fit - so a direct comparison with your application wouldn't be meaningful I'm afraid. Anyway, if I were you I wouldn't focus too much on the absolute value of the chi-square (if you definitely want to do it, @mtewes is more suited than I to talk about it), but more on how that value evolve with the initial time shift, and also on the plots. Could you show us what the spline+ml fit looks like now that you use a time shift of -55 days ?

**Comment by mtewes** [comment]
Hi all!

So indeed, the fits look bad, judging from the plot, not even the chi2 (at least with this time delay of 55 -- not sure about how bad it would look with -55, I haven't played with this data).
From the first plot (In [13] of the notebook) it seems that this delay is wrong indeed. The points just don't match. But I guess this is now resolved.

Regarding conlusion 1, question a): I don't think that there is a better strategy here. Do an optimisation with fixed true time delay and maybe a smaller ml_knotstep: if you can't "follow" the intrinsic curve by eye without having several datapoints along each "bump", than the sparsity and "noise" (fast ML) is just too high to allow for a meaningful point-estimate recovery of the delay. Increasing the number of knots (decreasing knotstep) significantly beyond what you did (knotstep=50, guessing this from your plots) would dilute the time delay signal even further.

Regarding b) : yes, in practice the spline is and should under-fit: we can't ask for "recovering" a critically-sampled intrinsic light curve, not-so-slow extrinsic stuff (which can't be modelled with the extrinsic splines), and time delays.
About the additional term: what is your motivation in "improving the fit" ?

Conclusion 2:
Yes, it is certainly hard for the spline method to discover delays in such data -- as expected :-/

PS: I saw the method timer.degree_of_freedom(). This seems roughly OK at first sight, but note that the number of knots changes with the initial time shift (due to the different footprint). But this shouldn't matter here, I'm commenting on it just FYI.

**Comment by chto** [comment]
Hi all, 
Thanks for the reply. 
@vbonvin 

>  variations seen in the image B are late by 55 days with respect to the variations in image A, right ?

Yep. That's right. 

> Could you show us what the spline+ml fit looks like now that you use a time shift of -55 days ?

Here it is. The parameter for the figure is knotstep=50, timedelay=-55, and the figure includes all of the data. 
<img width="1021" alt="sltimer_tdc2_analysis" src="https://cloud.githubusercontent.com/assets/16754618/20074035/7ded0e20-a4e3-11e6-9eb1-69d2c48d94bd.png">

@mtewes 

> yes, in practice the spline is and should under-fit... what is your motivation in "improving the fit" ?

Even spline function should be under-fit, but do we expect it under-fit a lot (as for this case, on average 30 sigma away from the data) ? 

Btw, I have another question. Do you have any suggestion on how do we choose knotstep parameter for intrinsic and extrinsic spline function? 

> I saw the method timer.degree_of_freedom(). This seems roughly OK at first sight, but note that the number of knots changes with the initial time shift (due to the different footprint). But this shouldn't matter here, I'm commenting on it just FYI.

Thank you very much for the reminders.

**Comment by mtewes** [comment]
Hi @chto,

ah, -55 looks better :) Whatever the convention is, this seems more likely to be the correct sign.

> Even spline function should be under-fit, but do we expect it under-fit a lot (as for this case, on average 30 sigma away from the data) ?

Yes! The spline model is based on the hypotheses that all light curve points originate from a single smooth intrinsic variability, some smooth "microlensing" (i.e., extrinsic) variability (smoother than the intrinsic one), and photometric noise (summarized by the error bars). Even for "easy" COSMOGRAIL curves, we _know_ that these assumptions are not absolutely right (that's why so much effort goes into the uncertainty estimation, adding fast extrinsic variability to the simulations etc). In the present case of TDC2, these assumptions really don't hold any more. It's a bit hard to see in the above light curve plot unless you stretch it out horizontally, but it seems to me that the points (probably from the different bands) of a single quasar image just don't match, and so we can't expect a good fit. The intrinsic quasar variability and also the microlensing are inherently different for the different bands.

> Btw, I have another question. Do you have any suggestion on how do we choose knotstep parameter for intrinsic and extrinsic spline function?

The theoretical answer (how we do it when using PyCS): given some carefully constructed simulated light curves, which mimic the observed data and for which we know the true delays, we _tune_ those knotsteps to get the best time-delay measurements on those simulations (see PyCS paper).
The practical answer: it's difficult to do so in this TDC2 case (one would first have to generate the sims). My advice is: select the knotsteps as low as possible so that the intrinsic spline manages to follow the signal that you "see" by eye, without starting to fit the probably-mostly-multi-band-related scatter.

**Comment by chto** [comment]
Hi, @mtewes 
Thank you very much for the reply and sorry for this late reply. It takes some time to think through all your points. 
But I still have one question. 

I agree that we can not expect pycs gives us a good fit because the data itself doesn't align with each other. But, the goal of spline function fitting is to find a time delay that gives us the minimum chisquare, which means spline method still relies on the goodness of fitting, right?  Therefore, by knowing that spline function can not fit the data very well, can we still say that the time-delay corresponding to the global minimum chisquare is the true time-delay?

**Comment by vbonvin** [comment]
Hi @chto ,

> Therefore, by knowing that spline function can not fit the data very well, can we still say that the time-delay corresponding to the global minimum chisquare is the true time-delay?

Anticipating a bit on @mtewes reply , that is not an easy question to answer - if answerable at all - otherwise we would have hit the mark at the TDC1 ! Part of the problem is that you don't know what is the best knotsteps for your spline fits: you might try to come up with a formula expressing the knotstep in function of the variability of your light curves, but doing so would be purely empirical and obviously subject to errors. 

Now, if you feel that your knotstep is in the good range, i.e. the spline fits look ok, then the delay corresponding to the global minimum chisquare of your procedure is certainly a good hint of what the true time-delay is. But if you see other local minimas in your chisquare-vs-timeshift plot, you should not trust blindly your first estimatition.

As an example, here is what I get applying my procedure on the light curves quoted above, with a knotstep of 50 (vertical grey line is the truth):
![tdc2-gateway1-ks50](https://cloud.githubusercontent.com/assets/12261805/20257668/5e40057e-aa4b-11e6-8d6a-cf66acad88e8.png)

Although the best value gives a true delay of zero, It seems to me that with that knotstep I'm not able to capture all the intrinsic variability of the curve. If I redo the procedure with a lower knotstep, say 32:

![tdc2-gateway1-ks32](https://cloud.githubusercontent.com/assets/12261805/20257717/bc469d18-aa4b-11e6-82eb-7e13256278f3.png)

It looks a bit different, now with a local minima around zero, another around -50 and the best fit at -110 (but that one was found with a high microlensing variability, I don't trust it much). And now if I use a knotstep of 20:

![tdc2-gateway1-ks20](https://cloud.githubusercontent.com/assets/12261805/20257785/3bb18978-aa4c-11e6-973a-a915da26d865.png)

And I find the right answer. But obviously in real life I don't know that, so I'll somehow have to chose between 0 and -55.

**Comment by mtewes** [comment]
Hi @chto ,

> by knowing that spline function can not fit the data very well, can we still say that the time-delay corresponding to the global minimum chisquare is the true time-delay?

I agree with @vbonvin that this is not that easy to answer, but I would say that it's mostly "no".
- For chosen reasonable knot densities (intrinsic and extrinsic), the true time delay certainly corresponds to a local minimum in chi square, if the data more or less fits to this simple spline model. This might not be the case with the plain _whitened_ TDC2 data.
- Depending on seasonal gaps, variability, and monitoring length, it is **very** likely that other, deeper, minima are found.
- Increasing the knot density (lower knotstep) to improve the chi square does in general not improve the quality of the time delay estimator.

**Comment by chto** [comment]
Hi @vbonvin  and @mtewes ,
Thank you very much. I get much more insight on spline fitting.

**Comment by drphilmarshall** [comment]
Thanks all for this most interesting discussion! In Vivien's knot step
comparison, I note that the peak chi-squared does improve when moving to
the knot step value that recovers better the true time delay - but I think
Chun-Hai I right to worry that unless the fit is "good" there are no
guarantees that you'll get an accurate result. I guess this is how a lot of
TDC 1 outliers arose.

One thing that should help is to include a new parameter describing the rms
dispersion of a n assumed "intrinsic noise" component. This will have te
effect of increasing the denominator of the chisquared so that chisq of
close to one is achievable. It will softeni the likelihood and give a
meaningful result when we factor in our H0 prior. @chto is on the case!

**Comment by chto** [comment]
Hi @drphilmarshall,
 Actually I am a little bit worried about adding the intrinsic noise term. 
Adding this intrinsic noise will wash out the quasar variability (especially if we want to make the chisquare match our prior) and make SLTimer even harder to find the true time delay. 

I think there are couples of possible reason to explain why chisquare is larger than we expected. First, for spline function, we assume the lightcurve is a smooth function of time, which is apparently not the case for TDC2. (For example, there are lots of gap in lightcurve.)
Second,  the gain for different band is different. 
Third, the microlensing effect is also different for different bands, and in SLTimer, we assume they are the same. 
Moreover, it's hard to test by only including data in one single band, because one single band contains so little data which makes our smooth lightcurve assumption even worse.
