### ISSUE TITLE
TDC2 Fermat Potential Prior

### ISSUE THREAD

**Issue by chto** [DarkEnergyScienceCollaboration/SLTimer#51]
From TDC2 simulation, we'll have the information about the Fermat Potential differences (as if from a lens model), and we can also assume a broad prior on $H_0$. 
I'll derive the formalism to use these priors and implement it in SLTimer.
I'll also make a short notebook to display the prior and overlap it with chisquares of the first gateway TDC2 dataset. The combination will be an approximation of the posterior PDF for the time delay.

* [ ] Sample the prior #54 
* [x] Integrate P(H_0) from 0 to inf #55 
* [ ] try different sigma_H0 #57  
* [ ] Extend sampling  quads #56
